// @ts-nocheck
/* eslint-disable */
/* Auto-generated by scripts/figma/icons/app.mjs — no Icon* prefix; names align with packages/icons/svg/{theme}/{stem}.svg + theme suffix (Outlined|Filled|TwoTone|Colored) */
import { figma } from '@figma/code-connect';
import {
  AccessOutlined,
  AccessPrimaryFilled,
  AccountAuditOutlined,
  AccountAuditPrimaryFilled,
  AccountLinkOutlined,
  AccountOutlined,
  AccountPrimaryFilled,
  AddOutlined,
  AdjustmentOutlined,
  AdjustmentPrimaryFilled,
  AimOutlined,
  AlertFilled,
  AlertOutlined,
  AlertPrimaryFilled,
  AliyunColored,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  AuditOutlined,
  AuditPrimaryFilled,
  AwsColored,
  AzOutlined,
  AzPrimaryFilled,
  AzureOutlined,
  BackupOutlined,
  BackupPrimaryFilled,
  BellOutlined,
  BellPrimaryFilled,
  BillOutlined,
  BillPrimaryFilled,
  BillingOutlined,
  BillingPrimaryFilled,
  BinaryOutlined,
  BulbOutlined,
  CalendarOutlined,
  CancelOutlined,
  CardOutlined,
  CardPrimaryFilled,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  ClearOutlined,
  CloudSyncOutlined,
  ClusterOutlined,
  ClusterPrimaryFilled,
  CodeSnippetOutlined,
  ColumnOutlined,
  CompatibilityOutlined,
  CompatibilityPrimaryFilled,
  ConfirmOutlined,
  CopyOutlined,
  CostOutlined,
  CostPrimaryFilled,
  CpuOutlined,
  CpuPrimaryFilled,
  DangerFilled,
  DangerPrimaryFilled,
  DataSyncPrimaryFilled,
  DatabaseOutlined,
  DatabasePrimaryFilled,
  DatahubColored,
  DatasourceOutlined,
  DatasourcePrimaryFilled,
  DatasyncFilled,
  DeleteOutlined,
  DevelopOutlined,
  DevelopPrimaryFilled,
  DiskOutlined,
  DiskPrimaryFilled,
  DistributedOutlined,
  DistributedPrimaryFilled,
  DocumentOutlined,
  DownDoubleOutlined,
  DownOutlined,
  DownSquareOutlined,
  DownloadOutlined,
  DragOutlined,
  DrillDownOutlined,
  DuplicateOutlined,
  DuplicatePrimaryFilled,
  EditOutlined,
  ErrorFilled,
  ErrorOutlined,
  ErrorPrimaryOutlined,
  EventOutlined,
  EventPrimaryFilled,
  ExpandOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileFolderOutlined,
  FileFolderPrimaryFilled,
  FileOutlined,
  FilePrimaryFilled,
  FilesOutlined,
  FilterOutlined,
  FoldOutlined,
  FolderOutOutlined,
  FolderOutlined,
  FullScreenExitOutlined,
  FullScreenOutlined,
  FunctionOutlined,
  GcpColored,
  GlyphColored,
  HelpOutlined,
  HelpPrimaryFilled,
  HomePageOutlined,
  HomePagePrimaryFilled,
  HostMachineOutlined,
  HostMachinePrimaryFilled,
  HuaweiLogoColored,
  IndexOutlined,
  InfoFilled,
  InfoOutlined,
  InfoPrimaryOutlined,
  IntegrationOutlined,
  IntegrationPrimaryFilled,
  InvoiceOutlined,
  InvoicePrimaryFilled,
  JobOutlined,
  KafkaColored,
  LanguageChOutlined,
  LanguageChtOutlined,
  LanguageEnOutlined,
  LanguageJpOutlined,
  LeftDoubleOutlined,
  LeftOutlined,
  LeftSquareOutlined,
  LifecycleFilled,
  LifecyclePrimaryFilled,
  LinkOutlined,
  LinkfileOutlined,
  ListOutlined,
  LoadingFilled,
  LoadingPrimaryOutlined,
  LoadingSpinnerOutlined,
  LocationOutlined,
  LockOutlined,
  LogDiskOutlined,
  LogDiskPrimaryFilled,
  LogOutlined,
  LogPrimaryFilled,
  LogoutOutlined,
  MachineRoomOutlined,
  MachineRoomPrimaryFilled,
  MemberPrimaryFilled,
  MembersOutlined,
  MemoryOutlined,
  MemoryPrimaryFilled,
  MenufoldOutlined,
  MenuunfoldOutlined,
  MfaOutlined,
  MfaPrimaryFilled,
  MigrationOutlined,
  MigrationPrimaryFilled,
  MinusOutlined,
  MinusSquareOutlined,
  MonitorFilled,
  MonitorLineChartOutlined,
  MonitorLineChartPrimaryFilled,
  MonitorOutlined,
  MoreHorizontalOutlined,
  MoreVerticalOutlined,
  MysqlColored,
  NetworkOutlined,
  NetworkPrimaryFilled,
  NetworkSettingOutlined,
  NetworkSettingPrimaryFilled,
  NewsOutlined,
  NewtickeOutlined,
  NewticketOutlined,
  NewticketPrimaryFilled,
  NodeOutlined,
  NodePrimaryFilled,
  NotificationBellOutlined,
  NumOutlined,
  OasOutlined,
  OasPrimaryFilled,
  ObProxyOutlined,
  ObProxyPrimaryFilled,
  OceanbaseColored,
  OneToOneOutlined,
  OperationOutlined,
  OperationPrimaryFilled,
  OpsOutlined,
  OpsPrimaryFilled,
  OracleColored,
  OrgOutlined,
  OrgPrimaryFilled,
  OverviewOutlined,
  OverviewPrimaryFilled,
  PackageBodyOutlined,
  PackageHeaderOutlined,
  PackageOutlined,
  ParameterOutlined,
  PartitionOutlined,
  PauseFilled,
  PauseOutlined,
  PerformanceOutlined,
  PerformancePrimaryFilled,
  PersonalSpaceOutlined,
  PersonalSpacePrimaryFilled,
  PgColored,
  PlscriptOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PolardbColored,
  ProcedureOutlined,
  ProductOutlined,
  ProductPrimaryFilled,
  ProjectOutlined,
  ProjectPrimaryFilled,
  QuestionOutlined,
  RedoFlatOutlined,
  RegionOutlined,
  RegionPrimaryFilled,
  ReloadOutlined,
  ReturnOutlined,
  RightDoubleOutlined,
  RightOutlined,
  RightSquareOutlined,
  RocketmqColored,
  SafetyOutlined,
  SafetyPrimaryFilled,
  SaveOutlined,
  SearchOutlined,
  SeekOutlined,
  SequenceOutlined,
  SettingOutlined,
  ShareOutlined,
  SnippetOutlined,
  SnippetPrimaryFilled,
  SortNegativeOutlined,
  SortOutlined,
  SortPositiveOutlined,
  SqlConsoleOutlined,
  SqlConsolePrimaryFilled,
  SqlLineChartOutlined,
  SqlScriptOutlined,
  StarOutlined,
  StringOutlined,
  SubProgramOutlined,
  SubscriptionOutlined,
  SubscriptionPrimaryFilled,
  SuccessFilled,
  SuccessOutlined,
  SuccessPrimaryOutlined,
  SupportOutlined,
  SupportPrimaryFilled,
  SwitchOutlined,
  SyncOutlined,
  SynonymsOutlined,
  TableOutlined,
  TagOutlined,
  TagPrimaryFilled,
  TaskOutlined,
  TaskPrimaryFilled,
  TeamSpaceOutlined,
  TeamSpacePrimaryFilled,
  TenantOutlined,
  TenantPrimaryFilled,
  TerminalOutlined,
  TerminateFilled,
  TicketPrimaryFilled,
  TidbColored,
  TimeOutlined,
  TimejobOutlined,
  TimezoneOutlined,
  TimezonePrimaryFilled,
  ToOutlined,
  TriggerOutlined,
  TutorialOutlined,
  TutorialPrimaryFilled,
  TutorialsOutlined,
  TypeOutlined,
  UndoFlatOutlined,
  UnitOutlined,
  UnitPrimaryFilled,
  UpDoubleOutlined,
  UpOutlined,
  UpSquareOutlined,
  UploadOutlined,
  UserOutlined,
  UserPrimaryFilled,
  UserSettingOutlined,
  UserSettingPrimaryFilled,
  VariableOutlined,
  VerificationOutlined,
  VerificationPrimaryFilled,
  ViewOutlined,
  WaitingFilled,
  WorkBenchPrimaryFilled,
  ZoneOutlined,
  ZonePrimaryFilled,
  ZoominOutlined,
  ZoomoutOutlined,
} from '@oceanbase/icons';

figma.connect(AccessOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2787', {
  example: () => <AccessOutlined />,
});
figma.connect(AccessPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2796', {
  example: () => <AccessPrimaryFilled />,
});
figma.connect(AccountAuditOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-271', {
  example: () => <AccountAuditOutlined />,
});
figma.connect(AccountAuditPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-260', {
  example: () => <AccountAuditPrimaryFilled />,
});
figma.connect(AccountLinkOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-210', {
  example: () => <AccountLinkOutlined />,
});
figma.connect(AccountOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3632', {
  example: () => <AccountOutlined />,
});
figma.connect(AccountPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-225', {
  example: () => <AccountPrimaryFilled />,
});
figma.connect(AddOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3371', {
  example: () => <AddOutlined />,
});
figma.connect(AdjustmentOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-968', {
  example: () => <AdjustmentOutlined />,
});
figma.connect(AdjustmentPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-961', {
  example: () => <AdjustmentPrimaryFilled />,
});
figma.connect(AimOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3372', {
  example: () => <AimOutlined />,
});
figma.connect(AlertFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2317', {
  example: () => <AlertFilled />,
});
figma.connect(AlertOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2303', {
  example: () => <AlertOutlined />,
});
figma.connect(AlertPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2310', {
  example: () => <AlertPrimaryFilled />,
});
figma.connect(AliyunColored, '<FIGMA_ICONS_BASE>?node-id=2255-5147', {
  example: () => <AliyunColored />,
});
figma.connect(ArrowDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-272', {
  example: () => <ArrowDownOutlined />,
});
figma.connect(ArrowLeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-274', {
  example: () => <ArrowLeftOutlined />,
});
figma.connect(ArrowRightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-276', {
  example: () => <ArrowRightOutlined />,
});
figma.connect(ArrowUpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-270', {
  example: () => <ArrowUpOutlined />,
});
figma.connect(AuditOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-183', {
  example: () => <AuditOutlined />,
});
figma.connect(AuditPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-193', {
  example: () => <AuditPrimaryFilled />,
});
figma.connect(AwsColored, '<FIGMA_ICONS_BASE>?node-id=2255-5102', {
  example: () => <AwsColored />,
});
figma.connect(AzOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2002', {
  example: () => <AzOutlined />,
});
figma.connect(AzPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1993', {
  example: () => <AzPrimaryFilled />,
});
figma.connect(AzureOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-5153', {
  example: () => <AzureOutlined />,
});
figma.connect(BackupOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-932', {
  example: () => <BackupOutlined />,
});
figma.connect(BackupPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-926', {
  example: () => <BackupPrimaryFilled />,
});
figma.connect(BellOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-721', {
  example: () => <BellOutlined />,
});
figma.connect(BellPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-715', {
  example: () => <BellPrimaryFilled />,
});
figma.connect(BillingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-741', {
  example: () => <BillingOutlined />,
});
figma.connect(BillingPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-736', {
  example: () => <BillingPrimaryFilled />,
});
figma.connect(BillOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-143', {
  example: () => <BillOutlined />,
});
figma.connect(BillPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-145', {
  example: () => <BillPrimaryFilled />,
});
figma.connect(BinaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3643', {
  example: () => <BinaryOutlined />,
});
figma.connect(BulbOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1028', {
  example: () => <BulbOutlined />,
});
figma.connect(CalendarOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3347', {
  example: () => <CalendarOutlined />,
});
figma.connect(CancelOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3337', {
  example: () => <CancelOutlined />,
});
figma.connect(CardOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-335', {
  example: () => <CardOutlined />,
});
figma.connect(CardPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-336', {
  example: () => <CardPrimaryFilled />,
});
figma.connect(CaretDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-281', {
  example: () => <CaretDownOutlined />,
});
figma.connect(CaretLeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-283', {
  example: () => <CaretLeftOutlined />,
});
figma.connect(CaretRightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-285', {
  example: () => <CaretRightOutlined />,
});
figma.connect(CaretUpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-279', {
  example: () => <CaretUpOutlined />,
});
figma.connect(ClearOutlined, '<FIGMA_ICONS_BASE>?node-id=5310-2267', {
  example: () => <ClearOutlined />,
});
figma.connect(CloudSyncOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3370', {
  example: () => <CloudSyncOutlined />,
});
figma.connect(ClusterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1814', {
  example: () => <ClusterOutlined />,
});
figma.connect(ClusterPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1810', {
  example: () => <ClusterPrimaryFilled />,
});
figma.connect(CodeSnippetOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3647', {
  example: () => <CodeSnippetOutlined />,
});
figma.connect(ColumnOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3634', {
  example: () => <ColumnOutlined />,
});
figma.connect(CompatibilityOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1474', {
  example: () => <CompatibilityOutlined />,
});
figma.connect(CompatibilityPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1467', {
  example: () => <CompatibilityPrimaryFilled />,
});
figma.connect(ConfirmOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3338', {
  example: () => <ConfirmOutlined />,
});
figma.connect(CopyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3381', {
  example: () => <CopyOutlined />,
});
figma.connect(CostOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-173', {
  example: () => <CostOutlined />,
});
figma.connect(CostPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-178', {
  example: () => <CostPrimaryFilled />,
});
figma.connect(CpuOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2180', {
  example: () => <CpuOutlined />,
});
figma.connect(CpuPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2167', {
  example: () => <CpuPrimaryFilled />,
});
figma.connect(DangerFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2407', {
  example: () => <DangerFilled />,
});
figma.connect(DangerPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2400', {
  example: () => <DangerPrimaryFilled />,
});
figma.connect(DatabaseOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1926', {
  example: () => <DatabaseOutlined />,
});
figma.connect(DatabasePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1918', {
  example: () => <DatabasePrimaryFilled />,
});
figma.connect(DatahubColored, '<FIGMA_ICONS_BASE>?node-id=2255-5036', {
  example: () => <DatahubColored />,
});
figma.connect(DatasourceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1160', {
  example: () => <DatasourceOutlined />,
});
figma.connect(DatasourcePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1151', {
  example: () => <DatasourcePrimaryFilled />,
});
figma.connect(DatasyncFilled, '<FIGMA_ICONS_BASE>?node-id=2088-3375', {
  example: () => <DatasyncFilled />,
});
figma.connect(DataSyncPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1137', {
  example: () => <DataSyncPrimaryFilled />,
});
figma.connect(DeleteOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3377', {
  example: () => <DeleteOutlined />,
});
figma.connect(DevelopOutlined, '<FIGMA_ICONS_BASE>?node-id=2418-1119', {
  example: () => <DevelopOutlined />,
});
figma.connect(DevelopPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2418-1121', {
  example: () => <DevelopPrimaryFilled />,
});
figma.connect(DiskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2215', {
  example: () => <DiskOutlined />,
});
figma.connect(DiskPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2206', {
  example: () => <DiskPrimaryFilled />,
});
figma.connect(DistributedOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1521', {
  example: () => <DistributedOutlined />,
});
figma.connect(DistributedPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1511', {
  example: () => <DistributedPrimaryFilled />,
});
figma.connect(DocumentOutlined, '<FIGMA_ICONS_BASE>?node-id=2347-1391', {
  example: () => <DocumentOutlined />,
});
figma.connect(DownDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12865', {
  example: () => <DownDoubleOutlined />,
});
figma.connect(DownloadOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3380', {
  example: () => <DownloadOutlined />,
});
figma.connect(DownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-263', {
  example: () => <DownOutlined />,
});
figma.connect(DownSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-294', {
  example: () => <DownSquareOutlined />,
});
figma.connect(DragOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3344', {
  example: () => <DragOutlined />,
});
figma.connect(DrillDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3343', {
  example: () => <DrillDownOutlined />,
});
figma.connect(DuplicateOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2110', {
  example: () => <DuplicateOutlined />,
});
figma.connect(DuplicatePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2104', {
  example: () => <DuplicatePrimaryFilled />,
});
figma.connect(EditOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3340', {
  example: () => <EditOutlined />,
});
figma.connect(ErrorFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2336', {
  example: () => <ErrorFilled />,
});
figma.connect(ErrorOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2323', {
  example: () => <ErrorOutlined />,
});
figma.connect(ErrorPrimaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2330', {
  example: () => <ErrorPrimaryOutlined />,
});
figma.connect(EventOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-765', {
  example: () => <EventOutlined />,
});
figma.connect(EventPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-757', {
  example: () => <EventPrimaryFilled />,
});
figma.connect(ExpandOutlined, '<FIGMA_ICONS_BASE>?node-id=2305-1984', {
  example: () => <ExpandOutlined />,
});
figma.connect(ExportOutlined, '<FIGMA_ICONS_BASE>?node-id=2317-399', {
  example: () => <ExportOutlined />,
});
figma.connect(EyeInvisibleOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3385', {
  example: () => <EyeInvisibleOutlined />,
});
figma.connect(EyeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3351', {
  example: () => <EyeOutlined />,
});
figma.connect(FileFolderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3342', {
  example: () => <FileFolderOutlined />,
});
figma.connect(FileFolderPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1531', {
  example: () => <FileFolderPrimaryFilled />,
});
figma.connect(FileOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3358', {
  example: () => <FileOutlined />,
});
figma.connect(FilePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-816', {
  example: () => <FilePrimaryFilled />,
});
figma.connect(FilesOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-823', {
  example: () => <FilesOutlined />,
});
figma.connect(FilterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3438', {
  example: () => <FilterOutlined />,
});
figma.connect(FolderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3361', {
  example: () => <FolderOutlined />,
});
figma.connect(FolderOutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1534', {
  example: () => <FolderOutOutlined />,
});
figma.connect(FoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2305-1985', {
  example: () => <FoldOutlined />,
});
figma.connect(FullScreenExitOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3382', {
  example: () => <FullScreenExitOutlined />,
});
figma.connect(FullScreenOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3387', {
  example: () => <FullScreenOutlined />,
});
figma.connect(FunctionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3642', {
  example: () => <FunctionOutlined />,
});
figma.connect(GcpColored, '<FIGMA_ICONS_BASE>?node-id=2255-5121', {
  example: () => <GcpColored />,
});
figma.connect(GlyphColored, '<FIGMA_ICONS_BASE>?node-id=2255-5128', {
  example: () => <GlyphColored />,
});
figma.connect(HelpOutlined, '<FIGMA_ICONS_BASE>?node-id=2845-5180', {
  example: () => <HelpOutlined />,
});
figma.connect(HelpPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1024', {
  example: () => <HelpPrimaryFilled />,
});
figma.connect(HomePageOutlined, '<FIGMA_ICONS_BASE>?node-id=2320-400', {
  example: () => <HomePageOutlined />,
});
figma.connect(HomePagePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2320-398', {
  example: () => <HomePagePrimaryFilled />,
});
figma.connect(HostMachineOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1872', {
  example: () => <HostMachineOutlined />,
});
figma.connect(HostMachinePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1862', {
  example: () => <HostMachinePrimaryFilled />,
});
figma.connect(HuaweiLogoColored, '<FIGMA_ICONS_BASE>?node-id=2255-5136', {
  example: () => <HuaweiLogoColored />,
});
figma.connect(IndexOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3654', {
  example: () => <IndexOutlined />,
});
figma.connect(InfoFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2372', {
  example: () => <InfoFilled />,
});
figma.connect(InfoOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2358', {
  example: () => <InfoOutlined />,
});
figma.connect(InfoPrimaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2365', {
  example: () => <InfoPrimaryOutlined />,
});
figma.connect(IntegrationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1321', {
  example: () => <IntegrationOutlined />,
});
figma.connect(IntegrationPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1316', {
  example: () => <IntegrationPrimaryFilled />,
});
figma.connect(InvoiceOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-159', {
  example: () => <InvoiceOutlined />,
});
figma.connect(InvoicePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-166', {
  example: () => <InvoicePrimaryFilled />,
});
figma.connect(JobOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3635', {
  example: () => <JobOutlined />,
});
figma.connect(KafkaColored, '<FIGMA_ICONS_BASE>?node-id=2255-5061', {
  example: () => <KafkaColored />,
});
figma.connect(LanguageChOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-343', {
  example: () => <LanguageChOutlined />,
});
figma.connect(LanguageChtOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1098', {
  example: () => <LanguageChtOutlined />,
});
figma.connect(LanguageEnOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-344', {
  example: () => <LanguageEnOutlined />,
});
figma.connect(LanguageJpOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-345', {
  example: () => <LanguageJpOutlined />,
});
figma.connect(LeftDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12867', {
  example: () => <LeftDoubleOutlined />,
});
figma.connect(LeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-265', {
  example: () => <LeftOutlined />,
});
figma.connect(LeftSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-300', {
  example: () => <LeftSquareOutlined />,
});
figma.connect(LifecycleFilled, '<FIGMA_ICONS_BASE>?node-id=2088-3352', {
  example: () => <LifecycleFilled />,
});
figma.connect(LifecyclePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2359-1422', {
  example: () => <LifecyclePrimaryFilled />,
});
figma.connect(LinkfileOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3348', {
  example: () => <LinkfileOutlined />,
});
figma.connect(LinkOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3349', {
  example: () => <LinkOutlined />,
});
figma.connect(ListOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3364', {
  example: () => <ListOutlined />,
});
figma.connect(LoadingFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2392', {
  example: () => <LoadingFilled />,
});
figma.connect(LoadingPrimaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2390', {
  example: () => <LoadingPrimaryOutlined />,
});
figma.connect(LoadingSpinnerOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2385', {
  example: () => <LoadingSpinnerOutlined />,
});
figma.connect(LocationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3373', {
  example: () => <LocationOutlined />,
});
figma.connect(LockOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3366', {
  example: () => <LockOutlined />,
});
figma.connect(LogDiskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2239', {
  example: () => <LogDiskOutlined />,
});
figma.connect(LogDiskPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2232', {
  example: () => <LogDiskPrimaryFilled />,
});
figma.connect(LogOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-948', {
  example: () => <LogOutlined />,
});
figma.connect(LogoutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3354', {
  example: () => <LogoutOutlined />,
});
figma.connect(LogPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-943', {
  example: () => <LogPrimaryFilled />,
});
figma.connect(MachineRoomOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2064', {
  example: () => <MachineRoomOutlined />,
});
figma.connect(MachineRoomPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2048', {
  example: () => <MachineRoomPrimaryFilled />,
});
figma.connect(MemberPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-844', {
  example: () => <MemberPrimaryFilled />,
});
figma.connect(MembersOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1216', {
  example: () => <MembersOutlined />,
});
figma.connect(MemoryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2141', {
  example: () => <MemoryOutlined />,
});
figma.connect(MemoryPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2131', {
  example: () => <MemoryPrimaryFilled />,
});
figma.connect(MenufoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3365', {
  example: () => <MenufoldOutlined />,
});
figma.connect(MenuunfoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3378', {
  example: () => <MenuunfoldOutlined />,
});
figma.connect(MfaOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-98', {
  example: () => <MfaOutlined />,
});
figma.connect(MfaPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2502-93', {
  example: () => <MfaPrimaryFilled />,
});
figma.connect(MigrationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1124', {
  example: () => <MigrationOutlined />,
});
figma.connect(MigrationPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1119', {
  example: () => <MigrationPrimaryFilled />,
});
figma.connect(MinusOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3353', {
  example: () => <MinusOutlined />,
});
figma.connect(MinusSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3368', {
  example: () => <MinusSquareOutlined />,
});
figma.connect(MonitorFilled, '<FIGMA_ICONS_BASE>?node-id=2255-21', {
  example: () => <MonitorFilled />,
});
figma.connect(MonitorLineChartOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1180', {
  example: () => <MonitorLineChartOutlined />,
});
figma.connect(MonitorLineChartPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1176', {
  example: () => <MonitorLineChartPrimaryFilled />,
});
figma.connect(MonitorOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-22', {
  example: () => <MonitorOutlined />,
});
figma.connect(MoreHorizontalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3384', {
  example: () => <MoreHorizontalOutlined />,
});
figma.connect(MoreVerticalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3350', {
  example: () => <MoreVerticalOutlined />,
});
figma.connect(MysqlColored, '<FIGMA_ICONS_BASE>?node-id=2255-5049', {
  example: () => <MysqlColored />,
});
figma.connect(NetworkOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1081', {
  example: () => <NetworkOutlined />,
});
figma.connect(NetworkPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1058', {
  example: () => <NetworkPrimaryFilled />,
});
figma.connect(NetworkSettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2294-1156', {
  example: () => <NetworkSettingOutlined />,
});
figma.connect(NetworkSettingPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2294-1155', {
  example: () => <NetworkSettingPrimaryFilled />,
});
figma.connect(NewsOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-408', {
  example: () => <NewsOutlined />,
});
figma.connect(NewtickeOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2910', {
  example: () => <NewtickeOutlined />,
});
figma.connect(NewticketOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2850', {
  example: () => <NewticketOutlined />,
});
figma.connect(NewticketPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2834', {
  example: () => <NewticketPrimaryFilled />,
});
figma.connect(NodeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1896', {
  example: () => <NodeOutlined />,
});
figma.connect(NodePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1889', {
  example: () => <NodePrimaryFilled />,
});
figma.connect(NotificationBellOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-243', {
  example: () => <NotificationBellOutlined />,
});
figma.connect(NumOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3645', {
  example: () => <NumOutlined />,
});
figma.connect(OasOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-912', {
  example: () => <OasOutlined />,
});
figma.connect(OasPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-903', {
  example: () => <OasPrimaryFilled />,
});
figma.connect(ObProxyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1779', {
  example: () => <ObProxyOutlined />,
});
figma.connect(ObProxyPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1769', {
  example: () => <ObProxyPrimaryFilled />,
});
figma.connect(OceanbaseColored, '<FIGMA_ICONS_BASE>?node-id=2255-5043', {
  example: () => <OceanbaseColored />,
});
figma.connect(OneToOneOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3374', {
  example: () => <OneToOneOutlined />,
});
figma.connect(OperationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1446', {
  example: () => <OperationOutlined />,
});
figma.connect(OperationPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1442', {
  example: () => <OperationPrimaryFilled />,
});
figma.connect(OpsOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1407', {
  example: () => <OpsOutlined />,
});
figma.connect(OpsPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1399', {
  example: () => <OpsPrimaryFilled />,
});
figma.connect(OracleColored, '<FIGMA_ICONS_BASE>?node-id=2255-5055', {
  example: () => <OracleColored />,
});
figma.connect(OrgOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-797', {
  example: () => <OrgOutlined />,
});
figma.connect(OrgPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-787', {
  example: () => <OrgPrimaryFilled />,
});
figma.connect(OverviewOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-882', {
  example: () => <OverviewOutlined />,
});
figma.connect(OverviewPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-878', {
  example: () => <OverviewPrimaryFilled />,
});
figma.connect(PackageBodyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3656', {
  example: () => <PackageBodyOutlined />,
});
figma.connect(PackageHeaderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3640', {
  example: () => <PackageHeaderOutlined />,
});
figma.connect(PackageOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3653', {
  example: () => <PackageOutlined />,
});
figma.connect(ParameterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3649', {
  example: () => <ParameterOutlined />,
});
figma.connect(PartitionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3646', {
  example: () => <PartitionOutlined />,
});
figma.connect(PauseFilled, '<FIGMA_ICONS_BASE>?node-id=2255-43', {
  example: () => <PauseFilled />,
});
figma.connect(PauseOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-34', {
  example: () => <PauseOutlined />,
});
figma.connect(PerformanceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1490', {
  example: () => <PerformanceOutlined />,
});
figma.connect(PerformancePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1486', {
  example: () => <PerformancePrimaryFilled />,
});
figma.connect(PersonalSpaceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1233', {
  example: () => <PersonalSpaceOutlined />,
});
figma.connect(PersonalSpacePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1229', {
  example: () => <PersonalSpacePrimaryFilled />,
});
figma.connect(PgColored, '<FIGMA_ICONS_BASE>?node-id=2255-5085', { example: () => <PgColored /> });
figma.connect(PlscriptOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3631', {
  example: () => <PlscriptOutlined />,
});
figma.connect(PlusOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3362', {
  example: () => <PlusOutlined />,
});
figma.connect(PlusSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3356', {
  example: () => <PlusSquareOutlined />,
});
figma.connect(PolardbColored, '<FIGMA_ICONS_BASE>?node-id=2255-4997', {
  example: () => <PolardbColored />,
});
figma.connect(ProcedureOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3648', {
  example: () => <ProcedureOutlined />,
});
figma.connect(ProductOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1375', {
  example: () => <ProductOutlined />,
});
figma.connect(ProductPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1370', {
  example: () => <ProductPrimaryFilled />,
});
figma.connect(ProjectOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1258', {
  example: () => <ProjectOutlined />,
});
figma.connect(ProjectPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1250', {
  example: () => <ProjectPrimaryFilled />,
});
figma.connect(QuestionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2377', {
  example: () => <QuestionOutlined />,
});
figma.connect(RedoFlatOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3379', {
  example: () => <RedoFlatOutlined />,
});
figma.connect(RegionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1964', {
  example: () => <RegionOutlined />,
});
figma.connect(RegionPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1953', {
  example: () => <RegionPrimaryFilled />,
});
figma.connect(ReloadOutlined, '<FIGMA_ICONS_BASE>?node-id=2359-1410', {
  example: () => <ReloadOutlined />,
});
figma.connect(ReturnOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3641', {
  example: () => <ReturnOutlined />,
});
figma.connect(RightDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12869', {
  example: () => <RightDoubleOutlined />,
});
figma.connect(RightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-267', {
  example: () => <RightOutlined />,
});
figma.connect(RightSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-306', {
  example: () => <RightSquareOutlined />,
});
figma.connect(RocketmqColored, '<FIGMA_ICONS_BASE>?node-id=2255-5071', {
  example: () => <RocketmqColored />,
});
figma.connect(SafetyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1303', {
  example: () => <SafetyOutlined />,
});
figma.connect(SafetyPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1295', {
  example: () => <SafetyPrimaryFilled />,
});
figma.connect(SaveOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3359', {
  example: () => <SaveOutlined />,
});
figma.connect(SearchOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3383', {
  example: () => <SearchOutlined />,
});
figma.connect(SeekOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3386', {
  example: () => <SeekOutlined />,
});
figma.connect(SequenceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3633', {
  example: () => <SequenceOutlined />,
});
figma.connect(SettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3341', {
  example: () => <SettingOutlined />,
});
figma.connect(ShareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3346', {
  example: () => <ShareOutlined />,
});
figma.connect(SnippetOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1340', {
  example: () => <SnippetOutlined />,
});
figma.connect(SnippetPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1336', {
  example: () => <SnippetPrimaryFilled />,
});
figma.connect(SortNegativeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3435', {
  example: () => <SortNegativeOutlined />,
});
figma.connect(SortOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3437', {
  example: () => <SortOutlined />,
});
figma.connect(SortPositiveOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3434', {
  example: () => <SortPositiveOutlined />,
});
figma.connect(SqlConsoleOutlined, '<FIGMA_ICONS_BASE>?node-id=2418-1106', {
  example: () => <SqlConsoleOutlined />,
});
figma.connect(SqlConsolePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2418-1112', {
  example: () => <SqlConsolePrimaryFilled />,
});
figma.connect(SqlLineChartOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3357', {
  example: () => <SqlLineChartOutlined />,
});
figma.connect(SqlScriptOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3638', {
  example: () => <SqlScriptOutlined />,
});
figma.connect(StarOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3360', {
  example: () => <StarOutlined />,
});
figma.connect(StringOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3650', {
  example: () => <StringOutlined />,
});
figma.connect(SubProgramOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3651', {
  example: () => <SubProgramOutlined />,
});
figma.connect(SubscriptionOutlined, '<FIGMA_ICONS_BASE>?node-id=2359-1013', {
  example: () => <SubscriptionOutlined />,
});
figma.connect(SubscriptionPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2359-1039', {
  example: () => <SubscriptionPrimaryFilled />,
});
figma.connect(SuccessFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2353', {
  example: () => <SuccessFilled />,
});
figma.connect(SuccessOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2341', {
  example: () => <SuccessOutlined />,
});
figma.connect(SuccessPrimaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2347', {
  example: () => <SuccessPrimaryOutlined />,
});
figma.connect(SupportOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2780', {
  example: () => <SupportOutlined />,
});
figma.connect(SupportPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2783', {
  example: () => <SupportPrimaryFilled />,
});
figma.connect(SwitchOutlined, '<FIGMA_ICONS_BASE>?node-id=2320-409', {
  example: () => <SwitchOutlined />,
});
figma.connect(SyncOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1140', {
  example: () => <SyncOutlined />,
});
figma.connect(SynonymsOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3655', {
  example: () => <SynonymsOutlined />,
});
figma.connect(TableOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3657', {
  example: () => <TableOutlined />,
});
figma.connect(TagOutlined, '<FIGMA_ICONS_BASE>?node-id=2207-314', {
  example: () => <TagOutlined />,
});
figma.connect(TagPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2207-325', {
  example: () => <TagPrimaryFilled />,
});
figma.connect(TaskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-998', {
  example: () => <TaskOutlined />,
});
figma.connect(TaskPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-990', {
  example: () => <TaskPrimaryFilled />,
});
figma.connect(TeamSpaceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-855', {
  example: () => <TeamSpaceOutlined />,
});
figma.connect(TeamSpacePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1209', {
  example: () => <TeamSpacePrimaryFilled />,
});
figma.connect(TenantOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1842', {
  example: () => <TenantOutlined />,
});
figma.connect(TenantPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1834', {
  example: () => <TenantPrimaryFilled />,
});
figma.connect(TerminalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1355', {
  example: () => <TerminalOutlined />,
});
figma.connect(TerminateFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2421', {
  example: () => <TerminateFilled />,
});
figma.connect(TicketPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2911', {
  example: () => <TicketPrimaryFilled />,
});
figma.connect(TidbColored, '<FIGMA_ICONS_BASE>?node-id=2255-5029', {
  example: () => <TidbColored />,
});
figma.connect(TimejobOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3644', {
  example: () => <TimejobOutlined />,
});
figma.connect(TimeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3367', {
  example: () => <TimeOutlined />,
});
figma.connect(TimezoneOutlined, '<FIGMA_ICONS_BASE>?node-id=2294-1159', {
  example: () => <TimezoneOutlined />,
});
figma.connect(TimezonePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2294-1169', {
  example: () => <TimezonePrimaryFilled />,
});
figma.connect(ToOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3339', {
  example: () => <ToOutlined />,
});
figma.connect(TriggerOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3637', {
  example: () => <TriggerOutlined />,
});
figma.connect(TutorialOutlined, '<FIGMA_ICONS_BASE>?node-id=2288-1103', {
  example: () => <TutorialOutlined />,
});
figma.connect(TutorialPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2288-1102', {
  example: () => <TutorialPrimaryFilled />,
});
figma.connect(TutorialsOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-254', {
  example: () => <TutorialsOutlined />,
});
figma.connect(TypeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3636', {
  example: () => <TypeOutlined />,
});
figma.connect(UndoFlatOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3369', {
  example: () => <UndoFlatOutlined />,
});
figma.connect(UnitOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2087', {
  example: () => <UnitOutlined />,
});
figma.connect(UnitPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2083', {
  example: () => <UnitPrimaryFilled />,
});
figma.connect(UpDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12863', {
  example: () => <UpDoubleOutlined />,
});
figma.connect(UploadOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3355', {
  example: () => <UploadOutlined />,
});
figma.connect(UpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-261', { example: () => <UpOutlined /> });
figma.connect(UpSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-288', {
  example: () => <UpSquareOutlined />,
});
figma.connect(UserOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1014', {
  example: () => <UserOutlined />,
});
figma.connect(UserPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1011', {
  example: () => <UserPrimaryFilled />,
});
figma.connect(UserSettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1195', {
  example: () => <UserSettingOutlined />,
});
figma.connect(UserSettingPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1191', {
  example: () => <UserSettingPrimaryFilled />,
});
figma.connect(VariableOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3639', {
  example: () => <VariableOutlined />,
});
figma.connect(VerificationOutlined, '<FIGMA_ICONS_BASE>?node-id=2357-2372', {
  example: () => <VerificationOutlined />,
});
figma.connect(VerificationPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2357-2394', {
  example: () => <VerificationPrimaryFilled />,
});
figma.connect(ViewOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3652', {
  example: () => <ViewOutlined />,
});
figma.connect(WaitingFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2413', {
  example: () => <WaitingFilled />,
});
figma.connect(WorkBenchPrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1350', {
  example: () => <WorkBenchPrimaryFilled />,
});
figma.connect(ZoneOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2027', {
  example: () => <ZoneOutlined />,
});
figma.connect(ZonePrimaryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2020', {
  example: () => <ZonePrimaryFilled />,
});
figma.connect(ZoominOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3376', {
  example: () => <ZoominOutlined />,
});
figma.connect(ZoomoutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3363', {
  example: () => <ZoomoutOutlined />,
});
