// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ob-batch-operation-bar': string;
  'ob-batch-operation-bar-cancel': string;
  'ob-batch-operation-bar-content': string;
  'ob-batch-operation-bar-content-active': string;
  'ob-batch-operation-bar-content-hidden': string;
  'ob-batch-operation-bar-display-btn': string;
  'ob-batch-operation-bar-display-text': string;
  'ob-batch-operation-bar-header': string;
  'ob-batch-operation-bar-title': string;
}
export const cssExports: CssExports;
export default cssExports;
