// @ts-nocheck
/* eslint-disable */
/* Auto-generated by skills/figma-code-connect/scripts/figma-icons.ts — no Icon* prefix; names align with packages/icons/svg/{theme}/…/{stem}.svg + theme suffix (Outlined|Filled|TwoTone|Colored); palette folders (e.g. gray) become nested dirs + kebab stem prefix */
import { figma } from '@figma/code-connect';
import {
  AccessFilled,
  AccessOutlined,
  AccountAuditFilled,
  AccountAuditOutlined,
  AccountFilled,
  AccountLinkOutlined,
  AccountOutlined,
  AdjustmentFilled,
  AdjustmentOutlined,
  AimOutlined,
  AlertFilled,
  AlertOutlined,
  AliyunColored,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  AuditFilled,
  AuditOutlined,
  AwsColored,
  AzFilled,
  AzOutlined,
  AzureOutlined,
  BackupFilled,
  BackupOutlined,
  BellFilled,
  BellOutlined,
  BillFilled,
  BillOutlined,
  BillingOutlined,
  BillingTwoTone,
  BinaryOutlined,
  BulbOutlined,
  CalendarOutlined,
  CardFilled,
  CardOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CheckOutlined,
  ClearOutlined,
  CloseOutlined,
  CloudSyncOutlined,
  ClusterFilled,
  ClusterOutlined,
  CodeSnippetOutlined,
  ColumnOutlined,
  CompatibilityFilled,
  CompatibilityOutlined,
  CopyOutlined,
  CostFilled,
  CostOutlined,
  CpuFilled,
  CpuOutlined,
  DangerFilled,
  DataSyncFilled,
  DataSyncOutlined,
  DatabaseFilled,
  DatabaseOutlined,
  DatahubColored,
  DatasourceFilled,
  DatasourceOutlined,
  DeleteOutlined,
  DevelopFilled,
  DevelopOutlined,
  DiskFilled,
  DiskOutlined,
  DistributedFilled,
  DistributedOutlined,
  DocumentOutlined,
  DownDoubleOutlined,
  DownOutlined,
  DownSquareOutlined,
  DownloadOutlined,
  DragHandleOutlined,
  DrillDownOutlined,
  DuplicateFilled,
  DuplicateOutlined,
  EditOutlined,
  ErrorFilled,
  ErrorOutlined,
  EventFilled,
  EventOutlined,
  ExpandOutlined,
  ExportOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FileFilled,
  FileFolderFilled,
  FileFolderOutlined,
  FileOutlined,
  FileSearchOutlined,
  FilesOutlined,
  FilterOutlined,
  FoldOutlined,
  FolderOutOutlined,
  FolderOutlined,
  FullScreenExitOutlined,
  FullScreenOutlined,
  FunctionOutlined,
  GcpColored,
  GlyphColored,
  HelpFilled,
  HelpOutlined,
  HomePageFilled,
  HomePageOutlined,
  HostMachineFilled,
  HostMachineOutlined,
  HuaweiLogoColored,
  IndexOutlined,
  InfoFilled,
  InfoOutlined,
  IntegrationFilled,
  IntegrationOutlined,
  InvoiceFilled,
  InvoiceOutlined,
  JobOutlined,
  KafkaColored,
  LanguageChOutlined,
  LanguageChtOutlined,
  LanguageEnOutlined,
  LanguageJpOutlined,
  LeftDoubleOutlined,
  LeftOutlined,
  LeftSquareOutlined,
  LifecycleFilled,
  LinkOutlined,
  LinkfileOutlined,
  ListOutlined,
  LoadingFilled,
  LoadingSpinnerOutlined,
  LocationOutlined,
  LockOutlined,
  LogDiskFilled,
  LogDiskOutlined,
  LogFilled,
  LogOutlined,
  LogoutOutlined,
  MachineRoomFilled,
  MachineRoomOutlined,
  MemberFilled,
  MembersOutlined,
  MemoryFilled,
  MemoryOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  MfaFilled,
  MfaOutlined,
  MigrationFilled,
  MigrationOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  MonitorFilled,
  MonitorLineChartFilled,
  MonitorLineChartOutlined,
  MonitorOutlined,
  MoreHorizontalOutlined,
  MoreVerticalOutlined,
  MysqlColored,
  NetworkFilled,
  NetworkOutlined,
  NetworkSettingFilled,
  NetworkSettingOutlined,
  NewsOutlined,
  NewtickeOutlined,
  NewticketFilled,
  NewticketOutlined,
  NodeFilled,
  NodeOutlined,
  NotificationBellOutlined,
  NumOutlined,
  OasFilled,
  OasOutlined,
  ObProxyFilled,
  ObProxyOutlined,
  OceanbaseColored,
  OneToOneOutlined,
  OperationFilled,
  OperationOutlined,
  OpsFilled,
  OpsOutlined,
  OracleColored,
  OrgFilled,
  OrgOutlined,
  OverviewFilled,
  OverviewOutlined,
  PackageBodyOutlined,
  PackageHeaderOutlined,
  PackageOutlined,
  ParameterOutlined,
  PartitionOutlined,
  PauseFilled,
  PauseOutlined,
  PerformanceFilled,
  PerformanceOutlined,
  PersonalSpaceFilled,
  PersonalSpaceOutlined,
  PgColored,
  PlscriptOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  PolardbColored,
  ProcedureOutlined,
  ProductFilled,
  ProductOutlined,
  ProjectFilled,
  ProjectOutlined,
  QuestionOutlined,
  RedoFlatOutlined,
  RegionFilled,
  RegionOutlined,
  ReloadOutlined,
  ReturnOutlined,
  RightDoubleOutlined,
  RightOutlined,
  RightSquareOutlined,
  RocketmqColored,
  SafetyFilled,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SequenceOutlined,
  SettingOutlined,
  ShareAltOutlined,
  SnippetFilled,
  SnippetOutlined,
  SortNegativeOutlined,
  SortOutlined,
  SortPositiveOutlined,
  SqlConsoleFilled,
  SqlConsoleOutlined,
  SqlLineChartOutlined,
  SqlScriptOutlined,
  StarOutlined,
  StringOutlined,
  SubProgramOutlined,
  SubscriptionFilled,
  SubscriptionOutlined,
  SuccessFilled,
  SuccessOutlined,
  SupportFilled,
  SupportOutlined,
  SwitchOutlined,
  SyncOutlined,
  SynonymsOutlined,
  TableOutlined,
  TagFilled,
  TagOutlined,
  TaskFilled,
  TaskOutlined,
  TeamSpaceFilled,
  TeamSpaceOutlined,
  TenantFilled,
  TenantOutlined,
  TerminalOutlined,
  TerminateFilled,
  TicketFilled,
  TidbColored,
  TimeOutlined,
  TimejobOutlined,
  TimezoneFilled,
  TimezoneOutlined,
  ToOutlined,
  TriggerOutlined,
  TutorialFilled,
  TutorialOutlined,
  TutorialsOutlined,
  TypeOutlined,
  UndoFlatOutlined,
  UnitFilled,
  UnitOutlined,
  UpDoubleOutlined,
  UpOutlined,
  UpSquareOutlined,
  UploadOutlined,
  UserFilled,
  UserOutlined,
  UserSettingFilled,
  UserSettingOutlined,
  VariableOutlined,
  VerificationFilled,
  VerificationOutlined,
  ViewOutlined,
  WaitingFilled,
  WorkbenchFilled,
  ZoneFilled,
  ZoneOutlined,
  ZoomOutOutlined,
  ZoominOutlined,
} from '@oceanbase/icons';

figma.connect(AccessFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2796', {
  example: () => <AccessFilled />,
});
figma.connect(AccessOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2787', {
  example: () => <AccessOutlined />,
});
figma.connect(AccountAuditFilled, '<FIGMA_ICONS_BASE>?node-id=2502-260', {
  example: () => <AccountAuditFilled />,
});
figma.connect(AccountAuditOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-271', {
  example: () => <AccountAuditOutlined />,
});
figma.connect(AccountFilled, '<FIGMA_ICONS_BASE>?node-id=2502-225', {
  example: () => <AccountFilled />,
});
figma.connect(AccountLinkOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-210', {
  example: () => <AccountLinkOutlined />,
});
figma.connect(AccountOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3632', {
  example: () => <AccountOutlined />,
});
figma.connect(AdjustmentFilled, '<FIGMA_ICONS_BASE>?node-id=2088-961', {
  example: () => <AdjustmentFilled />,
});
figma.connect(AdjustmentOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-968', {
  example: () => <AdjustmentOutlined />,
});
figma.connect(AimOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3372', {
  example: () => <AimOutlined />,
});
figma.connect(AlertFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2317', {
  example: () => <AlertFilled />,
});
figma.connect(AlertOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2303', {
  example: () => <AlertOutlined />,
});
figma.connect(AliyunColored, '<FIGMA_ICONS_BASE>?node-id=2255-5147', {
  example: () => <AliyunColored />,
});
figma.connect(ArrowDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-272', {
  example: () => <ArrowDownOutlined />,
});
figma.connect(ArrowLeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-274', {
  example: () => <ArrowLeftOutlined />,
});
figma.connect(ArrowRightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-276', {
  example: () => <ArrowRightOutlined />,
});
figma.connect(ArrowUpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-270', {
  example: () => <ArrowUpOutlined />,
});
figma.connect(AuditFilled, '<FIGMA_ICONS_BASE>?node-id=2502-193', {
  example: () => <AuditFilled />,
});
figma.connect(AuditOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-183', {
  example: () => <AuditOutlined />,
});
figma.connect(AwsColored, '<FIGMA_ICONS_BASE>?node-id=2255-5102', {
  example: () => <AwsColored />,
});
figma.connect(AzFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1993', { example: () => <AzFilled /> });
figma.connect(AzOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2002', {
  example: () => <AzOutlined />,
});
figma.connect(AzureOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-5153', {
  example: () => <AzureOutlined />,
});
figma.connect(BackupFilled, '<FIGMA_ICONS_BASE>?node-id=2088-926', {
  example: () => <BackupFilled />,
});
figma.connect(BackupOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-932', {
  example: () => <BackupOutlined />,
});
figma.connect(BellFilled, '<FIGMA_ICONS_BASE>?node-id=2088-715', { example: () => <BellFilled /> });
figma.connect(BellOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-721', {
  example: () => <BellOutlined />,
});
figma.connect(BillFilled, '<FIGMA_ICONS_BASE>?node-id=2502-145', { example: () => <BillFilled /> });
figma.connect(BillingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-741', {
  example: () => <BillingOutlined />,
});
figma.connect(BillingTwoTone, '<FIGMA_ICONS_BASE>?node-id=2088-736', {
  example: () => <BillingTwoTone />,
});
figma.connect(BillOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-143', {
  example: () => <BillOutlined />,
});
figma.connect(BinaryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3643', {
  example: () => <BinaryOutlined />,
});
figma.connect(BulbOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1028', {
  example: () => <BulbOutlined />,
});
figma.connect(CalendarOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3347', {
  example: () => <CalendarOutlined />,
});
figma.connect(CardFilled, '<FIGMA_ICONS_BASE>?node-id=2502-336', { example: () => <CardFilled /> });
figma.connect(CardOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-335', {
  example: () => <CardOutlined />,
});
figma.connect(CaretDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-281', {
  example: () => <CaretDownOutlined />,
});
figma.connect(CaretLeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-283', {
  example: () => <CaretLeftOutlined />,
});
figma.connect(CaretRightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-285', {
  example: () => <CaretRightOutlined />,
});
figma.connect(CaretUpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-279', {
  example: () => <CaretUpOutlined />,
});
figma.connect(CheckOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3338', {
  example: () => <CheckOutlined />,
});
figma.connect(ClearOutlined, '<FIGMA_ICONS_BASE>?node-id=5310-2267', {
  example: () => <ClearOutlined />,
});
figma.connect(CloseOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3337', {
  example: () => <CloseOutlined />,
});
figma.connect(CloudSyncOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3370', {
  example: () => <CloudSyncOutlined />,
});
figma.connect(ClusterFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1810', {
  example: () => <ClusterFilled />,
});
figma.connect(ClusterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1814', {
  example: () => <ClusterOutlined />,
});
figma.connect(CodeSnippetOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3647', {
  example: () => <CodeSnippetOutlined />,
});
figma.connect(ColumnOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3634', {
  example: () => <ColumnOutlined />,
});
figma.connect(CompatibilityFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1467', {
  example: () => <CompatibilityFilled />,
});
figma.connect(CompatibilityOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1474', {
  example: () => <CompatibilityOutlined />,
});
figma.connect(CopyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3381', {
  example: () => <CopyOutlined />,
});
figma.connect(CostFilled, '<FIGMA_ICONS_BASE>?node-id=2502-178', { example: () => <CostFilled /> });
figma.connect(CostOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-173', {
  example: () => <CostOutlined />,
});
figma.connect(CpuFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2167', { example: () => <CpuFilled /> });
figma.connect(CpuOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2180', {
  example: () => <CpuOutlined />,
});
figma.connect(DangerFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2407', {
  example: () => <DangerFilled />,
});
figma.connect(DangerFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2400', {
  example: () => <AlertOutlined />,
});
figma.connect(DatabaseFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1918', {
  example: () => <DatabaseFilled />,
});
figma.connect(DatabaseOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1926', {
  example: () => <DatabaseOutlined />,
});
figma.connect(DatahubColored, '<FIGMA_ICONS_BASE>?node-id=2255-5036', {
  example: () => <DatahubColored />,
});
figma.connect(DatasourceFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1151', {
  example: () => <DatasourceFilled />,
});
figma.connect(DatasourceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1160', {
  example: () => <DatasourceOutlined />,
});
figma.connect(DataSyncFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1137', {
  example: () => <DataSyncFilled />,
});
figma.connect(DataSyncOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3375', {
  example: () => <DataSyncOutlined />,
});
figma.connect(DeleteOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3377', {
  example: () => <DeleteOutlined />,
});
figma.connect(DevelopFilled, '<FIGMA_ICONS_BASE>?node-id=2418-1121', {
  example: () => <DevelopFilled />,
});
figma.connect(DevelopOutlined, '<FIGMA_ICONS_BASE>?node-id=2418-1119', {
  example: () => <DevelopOutlined />,
});
figma.connect(DiskFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2206', {
  example: () => <DiskFilled />,
});
figma.connect(DiskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2215', {
  example: () => <DiskOutlined />,
});
figma.connect(DistributedFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1511', {
  example: () => <DistributedFilled />,
});
figma.connect(DistributedOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1521', {
  example: () => <DistributedOutlined />,
});
figma.connect(DocumentOutlined, '<FIGMA_ICONS_BASE>?node-id=2347-1391', {
  example: () => <DocumentOutlined />,
});
figma.connect(DownDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12865', {
  example: () => <DownDoubleOutlined />,
});
figma.connect(DownloadOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3380', {
  example: () => <DownloadOutlined />,
});
figma.connect(DownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-263', {
  example: () => <DownOutlined />,
});
figma.connect(DownSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-294', {
  example: () => <DownSquareOutlined />,
});
figma.connect(DragHandleOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3344', {
  example: () => <DragHandleOutlined />,
});
figma.connect(DrillDownOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3343', {
  example: () => <DrillDownOutlined />,
});
figma.connect(DuplicateFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2104', {
  example: () => <DuplicateFilled />,
});
figma.connect(DuplicateOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2110', {
  example: () => <DuplicateOutlined />,
});
figma.connect(EditOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3340', {
  example: () => <EditOutlined />,
});
figma.connect(ErrorFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2336', {
  example: () => <ErrorFilled />,
});
figma.connect(ErrorOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2323', {
  example: () => <ErrorOutlined />,
});
figma.connect(EventFilled, '<FIGMA_ICONS_BASE>?node-id=2088-757', {
  example: () => <EventFilled />,
});
figma.connect(EventOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-765', {
  example: () => <EventOutlined />,
});
figma.connect(ExpandOutlined, '<FIGMA_ICONS_BASE>?node-id=2305-1984', {
  example: () => <ExpandOutlined />,
});
figma.connect(ExportOutlined, '<FIGMA_ICONS_BASE>?node-id=2317-399', {
  example: () => <ExportOutlined />,
});
figma.connect(EyeInvisibleOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3385', {
  example: () => <EyeInvisibleOutlined />,
});
figma.connect(EyeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3351', {
  example: () => <EyeOutlined />,
});
figma.connect(FileFilled, '<FIGMA_ICONS_BASE>?node-id=2088-816', { example: () => <FileFilled /> });
figma.connect(FileFolderFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1531', {
  example: () => <FileFolderFilled />,
});
figma.connect(FileFolderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3342', {
  example: () => <FileFolderOutlined />,
});
figma.connect(FileOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3358', {
  example: () => <FileOutlined />,
});
figma.connect(FileSearchOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3383', {
  example: () => <FileSearchOutlined />,
});
figma.connect(FilesOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-823', {
  example: () => <FilesOutlined />,
});
figma.connect(FilterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3438', {
  example: () => <FilterOutlined />,
});
figma.connect(FolderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3361', {
  example: () => <FolderOutlined />,
});
figma.connect(FolderOutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1534', {
  example: () => <FolderOutOutlined />,
});
figma.connect(FoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2305-1985', {
  example: () => <FoldOutlined />,
});
figma.connect(FullScreenExitOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3382', {
  example: () => <FullScreenExitOutlined />,
});
figma.connect(FullScreenOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3387', {
  example: () => <FullScreenOutlined />,
});
figma.connect(FunctionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3642', {
  example: () => <FunctionOutlined />,
});
figma.connect(GcpColored, '<FIGMA_ICONS_BASE>?node-id=2255-5121', {
  example: () => <GcpColored />,
});
figma.connect(GlyphColored, '<FIGMA_ICONS_BASE>?node-id=2255-5128', {
  example: () => <GlyphColored />,
});
figma.connect(HelpFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1024', {
  example: () => <HelpFilled />,
});
figma.connect(HelpOutlined, '<FIGMA_ICONS_BASE>?node-id=2845-5180', {
  example: () => <HelpOutlined />,
});
figma.connect(HomePageFilled, '<FIGMA_ICONS_BASE>?node-id=2320-398', {
  example: () => <HomePageFilled />,
});
figma.connect(HomePageOutlined, '<FIGMA_ICONS_BASE>?node-id=2320-400', {
  example: () => <HomePageOutlined />,
});
figma.connect(HostMachineFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1862', {
  example: () => <HostMachineFilled />,
});
figma.connect(HostMachineOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1872', {
  example: () => <HostMachineOutlined />,
});
figma.connect(HuaweiLogoColored, '<FIGMA_ICONS_BASE>?node-id=2255-5136', {
  example: () => <HuaweiLogoColored />,
});
figma.connect(IndexOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3654', {
  example: () => <IndexOutlined />,
});
figma.connect(InfoFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2372', {
  example: () => <InfoFilled />,
});
figma.connect(InfoOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2358', {
  example: () => <InfoOutlined />,
});
figma.connect(IntegrationFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1316', {
  example: () => <IntegrationFilled />,
});
figma.connect(IntegrationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1321', {
  example: () => <IntegrationOutlined />,
});
figma.connect(InvoiceFilled, '<FIGMA_ICONS_BASE>?node-id=2502-166', {
  example: () => <InvoiceFilled />,
});
figma.connect(InvoiceOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-159', {
  example: () => <InvoiceOutlined />,
});
figma.connect(JobOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3635', {
  example: () => <JobOutlined />,
});
figma.connect(KafkaColored, '<FIGMA_ICONS_BASE>?node-id=2255-5061', {
  example: () => <KafkaColored />,
});
figma.connect(LanguageChOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-343', {
  example: () => <LanguageChOutlined />,
});
figma.connect(LanguageChtOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1098', {
  example: () => <LanguageChtOutlined />,
});
figma.connect(LanguageEnOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-344', {
  example: () => <LanguageEnOutlined />,
});
figma.connect(LanguageJpOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-345', {
  example: () => <LanguageJpOutlined />,
});
figma.connect(LeftDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12867', {
  example: () => <LeftDoubleOutlined />,
});
figma.connect(LeftOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-265', {
  example: () => <LeftOutlined />,
});
figma.connect(LeftSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-300', {
  example: () => <LeftSquareOutlined />,
});
figma.connect(LifecycleFilled, '<FIGMA_ICONS_BASE>?node-id=2088-3352', {
  example: () => <LifecycleFilled />,
});
figma.connect(LifecycleFilled, '<FIGMA_ICONS_BASE>?node-id=2359-1422', {
  example: () => <LifecycleFilled />,
});
figma.connect(LinkfileOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3348', {
  example: () => <LinkfileOutlined />,
});
figma.connect(LinkOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3349', {
  example: () => <LinkOutlined />,
});
figma.connect(ListOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3364', {
  example: () => <ListOutlined />,
});
figma.connect(LoadingFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2392', {
  example: () => <LoadingFilled />,
});
figma.connect(LoadingSpinnerOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2385', {
  example: () => <LoadingSpinnerOutlined />,
});
figma.connect(LocationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3373', {
  example: () => <LocationOutlined />,
});
figma.connect(LockOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3366', {
  example: () => <LockOutlined />,
});
figma.connect(LogDiskFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2232', {
  example: () => <LogDiskFilled />,
});
figma.connect(LogDiskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2239', {
  example: () => <LogDiskOutlined />,
});
figma.connect(LogFilled, '<FIGMA_ICONS_BASE>?node-id=2088-943', { example: () => <LogFilled /> });
figma.connect(LogOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-948', {
  example: () => <LogOutlined />,
});
figma.connect(LogoutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3354', {
  example: () => <LogoutOutlined />,
});
figma.connect(MachineRoomFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2048', {
  example: () => <MachineRoomFilled />,
});
figma.connect(MachineRoomOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2064', {
  example: () => <MachineRoomOutlined />,
});
figma.connect(MemberFilled, '<FIGMA_ICONS_BASE>?node-id=2088-844', {
  example: () => <MemberFilled />,
});
figma.connect(MembersOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1216', {
  example: () => <MembersOutlined />,
});
figma.connect(MemoryFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2131', {
  example: () => <MemoryFilled />,
});
figma.connect(MemoryOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2141', {
  example: () => <MemoryOutlined />,
});
figma.connect(MenuFoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3365', {
  example: () => <MenuFoldOutlined />,
});
figma.connect(MenuUnfoldOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3378', {
  example: () => <MenuUnfoldOutlined />,
});
figma.connect(MfaFilled, '<FIGMA_ICONS_BASE>?node-id=2502-93', { example: () => <MfaFilled /> });
figma.connect(MfaOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-98', {
  example: () => <MfaOutlined />,
});
figma.connect(MigrationFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1119', {
  example: () => <MigrationFilled />,
});
figma.connect(MigrationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1124', {
  example: () => <MigrationOutlined />,
});
figma.connect(MinusOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3353', {
  example: () => <MinusOutlined />,
});
figma.connect(MinusSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3368', {
  example: () => <MinusSquareOutlined />,
});
figma.connect(MonitorFilled, '<FIGMA_ICONS_BASE>?node-id=2255-21', {
  example: () => <MonitorFilled />,
});
figma.connect(MonitorLineChartFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1176', {
  example: () => <MonitorLineChartFilled />,
});
figma.connect(MonitorLineChartOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1180', {
  example: () => <MonitorLineChartOutlined />,
});
figma.connect(MonitorOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-22', {
  example: () => <MonitorOutlined />,
});
figma.connect(MoreHorizontalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3384', {
  example: () => <MoreHorizontalOutlined />,
});
figma.connect(MoreVerticalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3350', {
  example: () => <MoreVerticalOutlined />,
});
figma.connect(MysqlColored, '<FIGMA_ICONS_BASE>?node-id=2255-5049', {
  example: () => <MysqlColored />,
});
figma.connect(NetworkFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1058', {
  example: () => <NetworkFilled />,
});
figma.connect(NetworkOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1081', {
  example: () => <NetworkOutlined />,
});
figma.connect(NetworkSettingFilled, '<FIGMA_ICONS_BASE>?node-id=2294-1155', {
  example: () => <NetworkSettingFilled />,
});
figma.connect(NetworkSettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2294-1156', {
  example: () => <NetworkSettingOutlined />,
});
figma.connect(NewsOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-408', {
  example: () => <NewsOutlined />,
});
figma.connect(NewtickeOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2910', {
  example: () => <NewtickeOutlined />,
});
figma.connect(NewticketFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2834', {
  example: () => <NewticketFilled />,
});
figma.connect(NewticketOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2850', {
  example: () => <NewticketOutlined />,
});
figma.connect(NodeFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1889', {
  example: () => <NodeFilled />,
});
figma.connect(NodeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1896', {
  example: () => <NodeOutlined />,
});
figma.connect(NotificationBellOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-243', {
  example: () => <NotificationBellOutlined />,
});
figma.connect(NumOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3645', {
  example: () => <NumOutlined />,
});
figma.connect(OasFilled, '<FIGMA_ICONS_BASE>?node-id=2088-903', { example: () => <OasFilled /> });
figma.connect(OasOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-912', {
  example: () => <OasOutlined />,
});
figma.connect(ObProxyFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1769', {
  example: () => <ObProxyFilled />,
});
figma.connect(ObProxyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1779', {
  example: () => <ObProxyOutlined />,
});
figma.connect(OceanbaseColored, '<FIGMA_ICONS_BASE>?node-id=2255-5043', {
  example: () => <OceanbaseColored />,
});
figma.connect(OneToOneOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3374', {
  example: () => <OneToOneOutlined />,
});
figma.connect(OperationFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1442', {
  example: () => <OperationFilled />,
});
figma.connect(OperationOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1446', {
  example: () => <OperationOutlined />,
});
figma.connect(OpsFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1399', { example: () => <OpsFilled /> });
figma.connect(OpsOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1407', {
  example: () => <OpsOutlined />,
});
figma.connect(OracleColored, '<FIGMA_ICONS_BASE>?node-id=2255-5055', {
  example: () => <OracleColored />,
});
figma.connect(OrgFilled, '<FIGMA_ICONS_BASE>?node-id=2088-787', { example: () => <OrgFilled /> });
figma.connect(OrgOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-797', {
  example: () => <OrgOutlined />,
});
figma.connect(OverviewFilled, '<FIGMA_ICONS_BASE>?node-id=2088-878', {
  example: () => <OverviewFilled />,
});
figma.connect(OverviewOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-882', {
  example: () => <OverviewOutlined />,
});
figma.connect(PackageBodyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3656', {
  example: () => <PackageBodyOutlined />,
});
figma.connect(PackageHeaderOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3640', {
  example: () => <PackageHeaderOutlined />,
});
figma.connect(PackageOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3653', {
  example: () => <PackageOutlined />,
});
figma.connect(ParameterOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3649', {
  example: () => <ParameterOutlined />,
});
figma.connect(PartitionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3646', {
  example: () => <PartitionOutlined />,
});
figma.connect(PauseFilled, '<FIGMA_ICONS_BASE>?node-id=2255-43', {
  example: () => <PauseFilled />,
});
figma.connect(PauseOutlined, '<FIGMA_ICONS_BASE>?node-id=2255-34', {
  example: () => <PauseOutlined />,
});
figma.connect(PerformanceFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1486', {
  example: () => <PerformanceFilled />,
});
figma.connect(PerformanceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1490', {
  example: () => <PerformanceOutlined />,
});
figma.connect(PersonalSpaceFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1229', {
  example: () => <PersonalSpaceFilled />,
});
figma.connect(PersonalSpaceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1233', {
  example: () => <PersonalSpaceOutlined />,
});
figma.connect(PgColored, '<FIGMA_ICONS_BASE>?node-id=2255-5085', { example: () => <PgColored /> });
figma.connect(PlscriptOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3631', {
  example: () => <PlscriptOutlined />,
});
figma.connect(PlusCircleOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3371', {
  example: () => <PlusCircleOutlined />,
});
figma.connect(PlusOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3362', {
  example: () => <PlusOutlined />,
});
figma.connect(PlusSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3356', {
  example: () => <PlusSquareOutlined />,
});
figma.connect(PolardbColored, '<FIGMA_ICONS_BASE>?node-id=2255-4997', {
  example: () => <PolardbColored />,
});
figma.connect(ProcedureOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3648', {
  example: () => <ProcedureOutlined />,
});
figma.connect(ProductFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1370', {
  example: () => <ProductFilled />,
});
figma.connect(ProductOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1375', {
  example: () => <ProductOutlined />,
});
figma.connect(ProjectFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1250', {
  example: () => <ProjectFilled />,
});
figma.connect(ProjectOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1258', {
  example: () => <ProjectOutlined />,
});
figma.connect(QuestionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2377', {
  example: () => <QuestionOutlined />,
});
figma.connect(RedoFlatOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3379', {
  example: () => <RedoFlatOutlined />,
});
figma.connect(RegionFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1953', {
  example: () => <RegionFilled />,
});
figma.connect(RegionOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1964', {
  example: () => <RegionOutlined />,
});
figma.connect(ReloadOutlined, '<FIGMA_ICONS_BASE>?node-id=2359-1410', {
  example: () => <ReloadOutlined />,
});
figma.connect(ReturnOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3641', {
  example: () => <ReturnOutlined />,
});
figma.connect(RightDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12869', {
  example: () => <RightDoubleOutlined />,
});
figma.connect(RightOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-267', {
  example: () => <RightOutlined />,
});
figma.connect(RightSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-306', {
  example: () => <RightSquareOutlined />,
});
figma.connect(RocketmqColored, '<FIGMA_ICONS_BASE>?node-id=2255-5071', {
  example: () => <RocketmqColored />,
});
figma.connect(SafetyFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1295', {
  example: () => <SafetyFilled />,
});
figma.connect(SafetyOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1303', {
  example: () => <SafetyOutlined />,
});
figma.connect(SaveOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3359', {
  example: () => <SaveOutlined />,
});
figma.connect(SearchOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3386', {
  example: () => <SearchOutlined />,
});
figma.connect(SequenceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3633', {
  example: () => <SequenceOutlined />,
});
figma.connect(SettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3341', {
  example: () => <SettingOutlined />,
});
figma.connect(ShareAltOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3346', {
  example: () => <ShareAltOutlined />,
});
figma.connect(SnippetFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1336', {
  example: () => <SnippetFilled />,
});
figma.connect(SnippetOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1340', {
  example: () => <SnippetOutlined />,
});
figma.connect(SortNegativeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3435', {
  example: () => <SortNegativeOutlined />,
});
figma.connect(SortOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3437', {
  example: () => <SortOutlined />,
});
figma.connect(SortPositiveOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3434', {
  example: () => <SortPositiveOutlined />,
});
figma.connect(SqlConsoleFilled, '<FIGMA_ICONS_BASE>?node-id=2418-1112', {
  example: () => <SqlConsoleFilled />,
});
figma.connect(SqlConsoleOutlined, '<FIGMA_ICONS_BASE>?node-id=2418-1106', {
  example: () => <SqlConsoleOutlined />,
});
figma.connect(SqlLineChartOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3357', {
  example: () => <SqlLineChartOutlined />,
});
figma.connect(SqlScriptOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3638', {
  example: () => <SqlScriptOutlined />,
});
figma.connect(StarOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3360', {
  example: () => <StarOutlined />,
});
figma.connect(StringOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3650', {
  example: () => <StringOutlined />,
});
figma.connect(SubProgramOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3651', {
  example: () => <SubProgramOutlined />,
});
figma.connect(SubscriptionFilled, '<FIGMA_ICONS_BASE>?node-id=2359-1039', {
  example: () => <SubscriptionFilled />,
});
figma.connect(SubscriptionOutlined, '<FIGMA_ICONS_BASE>?node-id=2359-1013', {
  example: () => <SubscriptionOutlined />,
});
figma.connect(SuccessFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2353', {
  example: () => <SuccessFilled />,
});
figma.connect(SuccessOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2341', {
  example: () => <SuccessOutlined />,
});
figma.connect(SupportFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2783', {
  example: () => <SupportFilled />,
});
figma.connect(SupportOutlined, '<FIGMA_ICONS_BASE>?node-id=2420-2780', {
  example: () => <SupportOutlined />,
});
figma.connect(SwitchOutlined, '<FIGMA_ICONS_BASE>?node-id=2320-409', {
  example: () => <SwitchOutlined />,
});
figma.connect(SyncOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1140', {
  example: () => <SyncOutlined />,
});
figma.connect(SynonymsOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3655', {
  example: () => <SynonymsOutlined />,
});
figma.connect(TableOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3657', {
  example: () => <TableOutlined />,
});
figma.connect(TagFilled, '<FIGMA_ICONS_BASE>?node-id=2207-325', { example: () => <TagFilled /> });
figma.connect(TagOutlined, '<FIGMA_ICONS_BASE>?node-id=2207-314', {
  example: () => <TagOutlined />,
});
figma.connect(TaskFilled, '<FIGMA_ICONS_BASE>?node-id=2088-990', { example: () => <TaskFilled /> });
figma.connect(TaskOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-998', {
  example: () => <TaskOutlined />,
});
figma.connect(TeamSpaceFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1209', {
  example: () => <TeamSpaceFilled />,
});
figma.connect(TeamSpaceOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-855', {
  example: () => <TeamSpaceOutlined />,
});
figma.connect(TenantFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1834', {
  example: () => <TenantFilled />,
});
figma.connect(TenantOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1842', {
  example: () => <TenantOutlined />,
});
figma.connect(TerminalOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1355', {
  example: () => <TerminalOutlined />,
});
figma.connect(TerminateFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2421', {
  example: () => <TerminateFilled />,
});
figma.connect(TicketFilled, '<FIGMA_ICONS_BASE>?node-id=2420-2911', {
  example: () => <TicketFilled />,
});
figma.connect(TidbColored, '<FIGMA_ICONS_BASE>?node-id=2255-5029', {
  example: () => <TidbColored />,
});
figma.connect(TimejobOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3644', {
  example: () => <TimejobOutlined />,
});
figma.connect(TimeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3367', {
  example: () => <TimeOutlined />,
});
figma.connect(TimezoneFilled, '<FIGMA_ICONS_BASE>?node-id=2294-1169', {
  example: () => <TimezoneFilled />,
});
figma.connect(TimezoneOutlined, '<FIGMA_ICONS_BASE>?node-id=2294-1159', {
  example: () => <TimezoneOutlined />,
});
figma.connect(ToOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3339', {
  example: () => <ToOutlined />,
});
figma.connect(TriggerOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3637', {
  example: () => <TriggerOutlined />,
});
figma.connect(TutorialFilled, '<FIGMA_ICONS_BASE>?node-id=2288-1102', {
  example: () => <TutorialFilled />,
});
figma.connect(TutorialOutlined, '<FIGMA_ICONS_BASE>?node-id=2288-1103', {
  example: () => <TutorialOutlined />,
});
figma.connect(TutorialsOutlined, '<FIGMA_ICONS_BASE>?node-id=2502-254', {
  example: () => <TutorialsOutlined />,
});
figma.connect(TypeOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3636', {
  example: () => <TypeOutlined />,
});
figma.connect(UndoFlatOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3369', {
  example: () => <UndoFlatOutlined />,
});
figma.connect(UnitFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2083', {
  example: () => <UnitFilled />,
});
figma.connect(UnitOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2087', {
  example: () => <UnitOutlined />,
});
figma.connect(UpDoubleOutlined, '<FIGMA_ICONS_BASE>?node-id=2424-12863', {
  example: () => <UpDoubleOutlined />,
});
figma.connect(UploadOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3355', {
  example: () => <UploadOutlined />,
});
figma.connect(UpOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-261', { example: () => <UpOutlined /> });
figma.connect(UpSquareOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-288', {
  example: () => <UpSquareOutlined />,
});
figma.connect(UserFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1011', {
  example: () => <UserFilled />,
});
figma.connect(UserOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1014', {
  example: () => <UserOutlined />,
});
figma.connect(UserSettingFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1191', {
  example: () => <UserSettingFilled />,
});
figma.connect(UserSettingOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-1195', {
  example: () => <UserSettingOutlined />,
});
figma.connect(VariableOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3639', {
  example: () => <VariableOutlined />,
});
figma.connect(VerificationFilled, '<FIGMA_ICONS_BASE>?node-id=2357-2394', {
  example: () => <VerificationFilled />,
});
figma.connect(VerificationOutlined, '<FIGMA_ICONS_BASE>?node-id=2357-2372', {
  example: () => <VerificationOutlined />,
});
figma.connect(ViewOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3652', {
  example: () => <ViewOutlined />,
});
figma.connect(WaitingFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2413', {
  example: () => <WaitingFilled />,
});
figma.connect(WorkbenchFilled, '<FIGMA_ICONS_BASE>?node-id=2088-1350', {
  example: () => <WorkbenchFilled />,
});
figma.connect(ZoneFilled, '<FIGMA_ICONS_BASE>?node-id=2088-2020', {
  example: () => <ZoneFilled />,
});
figma.connect(ZoneOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-2027', {
  example: () => <ZoneOutlined />,
});
figma.connect(ZoominOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3376', {
  example: () => <ZoominOutlined />,
});
figma.connect(ZoomOutOutlined, '<FIGMA_ICONS_BASE>?node-id=2088-3363', {
  example: () => <ZoomOutOutlined />,
});
