const defaultTheme = {
  token: {
    colorPrimaryBg: '#EAF1FF',
    colorPrimary: '#006AFF',
    colorPrimaryBgHover: '#EAF1FF',
    colorPrimaryBorder: '#B3CCFF',
    colorPrimaryBorderHover: '#5189FB',
    colorPrimaryHover: '#5189FB',
    colorPrimaryTextHover: '#5189FB',
    colorPrimaryText: '#006AFF',
    colorPrimaryTextActive: '#004CE6',
    colorSuccess: '#0ac185',
    colorSuccessBg: '#EEF8F5',
    colorSuccessBgHover: '#B3E6D5',
    colorSuccessBorder: '#B3E6D5',
    colorSuccessBorderHover: '#4DCCA2',
    colorSuccessHover: '#4DCCA2',
    colorSuccessActive: '#00B378',
    colorSuccessTextHover: '#4DCCA2',
    colorSuccessText: '#0AC185',
    colorSuccessTextActive: '#00B378',
    colorWarning: '#ffac33',
    colorWarningBg: '#FFF5E5',
    colorWarningBgHover: '#FFD699',
    colorWarningBorder: '#FFD699',
    colorWarningBorderHover: '#FFC166',
    colorWarningHover: '#FFC166',
    colorWarningActive: '#FF9700',
    colorWarningTextHover: '#FFC166',
    colorWarningText: '#FFAC33',
    colorWarningTextActive: '#FF9700',
    colorErrorBg: '#FFEBEB',
    colorErrorBgHover: '#FFB3B3',
    colorErrorBorder: '#FFB3B3',
    colorErrorBorderHover: '#FF8080',
    colorErrorHover: '#FF8080',
    colorErrorActive: '#EC1313',
    colorErrorTextHover: '#FF8080',
    colorErrorText: '#FF4B4B',
    colorErrorTextActive: '#EC1313',
    colorError: '#ff4b4b',
    colorInfo: '#006aff',
    colorInfoBg: '#EAF1FF',
    colorInfoBgHover: '#EAF1FF',
    colorInfoBorder: '#B3CCFF',
    colorInfoBorderHover: '#5189FB',
    colorInfoHover: '#5189FB',
    colorInfoActive: '#004CE6',
    colorInfoTextHover: '#5189FB',
    colorInfoText: '#006AFF',
    colorInfoTextActive: '#004CE6',
    colorTextBase: '#132039',
    colorBgBase: '#ffffff',
    colorText: '#132039',
    colorTextSecondary: '#5C6B8A',
    colorTextQuaternary: '#ABB7CF',
    colorTextTertiary: '#8592AD',
    colorBgContainer: '#ffffff',
    colorBgLayout: '#F8FAFE',
    colorBgSpotlight: 'rgba(19, 32, 57, 0.8)',
    colorBgMask: 'rgba(19, 32, 57,  0.6)',
    colorBorder: '#CDD5E4',
    colorBorderSecondary: '#E2E8F3',
    colorFillQuaternary: '#F8FAFE',
    colorFillTertiary: '#F8FAFE',
    colorFillSecondary: '#F3F6FC',
    colorFill: '#E2E8F3',
    boxShadowSecondary:
      '0 6px 16px 0 rgba(54, 69, 99, 0.08), 0 3px 6px -4px rgba(54, 69, 99, 0.12), 0 9px 28px 8px rgba(54, 69, 99, 0.05)',
    boxShadow:
      '0 1px 2px 0 rgba(54, 69, 99, 0.03), 0 1px 6px -1px rgba(54, 69, 99, 0.02), 0 2px 4px 0 rgba(54, 69, 99, 0.02)',
    borderRadius: 6,
    wireframe: false,
    colorPrimaryActive: '#004CE6',
  },
  components: {
    Dropdown: {
      colorError: '#FF4B4B',
    },
    Button: {
      borderRadius: 6,
    },
    Segmented: {
      itemColor: '#5C6B8A',
      itemHoverColor: '#132039',
      itemHoverBg: '#ffffff',
    },
    Rate: {
      colorFillContent: '#E2E8F3',
      colorText: '#F20000',
    },
    InputNumber: {
      handleVisible: true,
    },
  },
};

export default defaultTheme;
