// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  layoutRoot: string;
  layoutSider: string;
  siteLayoutBackground: string;
}
export const cssExports: CssExports;
export default cssExports;
